#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if command -v systemd-tmpfiles >/dev/null 2>&1; then
        systemd-tmpfiles --create wardd.conf || true
    fi

    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload || true
    fi
fi

exit 0
